---
- name: "Apply Templates"
  template:
    dest: "{{ item.dest }}"
    src:  "{{ (item.dest | basename ()) + '.j2' }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: "{{ install_lobalancer_templates[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
  tags:
    - lobalancer
