---
- name: "Apply Templates"
  template:
    dest: "{{ item.dest }}"
    src:  "{{ (item.dest | basename ()) + '.j2' }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
    - dest: "/usr/local/bin/lobalancer"
      mode: "0755"
    - dest: "/etc/systemd/system/lobalancer@.timer"
    - dest: "/etc/systemd/system/lobalancer@.service"
  when:
    - lobalancer is defined
  tags:
    - lobalancer
